### ISSUE TITLE
EWMA doesn't work?

### ISSUE THREAD

**Issue by is-sim** [MarinoMtz/lorawan_jamming#3]
Hi marino, I have run two different simulations: one by activating the EWMA parameter and the other by deactivating this parameter but the result of the two simulations is same.  Can you explain me why? 
 
Could you give me the right command to correctly activate the EWMA detection algorithm?

Thanks
BR

1 simulation) ./waf --run "scratch/lorawan-network-attack-multiple-GW --nGateways=2 --nJammers_up=50 --nJammers_dw=0 --JammerType=3 --nDevices=50 --PayloadSize=42 --Specific_SF=1 --ED_SF=7 --simulationTime=3600 --PayloadJamSize_up=42 --JammerTxPower=14 --Random_SF=0 --JammerDutyCycle_up=0.1 --JammerSF=7 --updw=0 --authpre=0 --Exponential=1 --Int_Model=4 --delta=6 --retransmission=1 --maxtx=1 --Conf_UP=1 --Net_Ser=1"

2 simulation) ./waf --run "scratch/lorawan-network-attack-multiple-GW --nGateways=2 --nJammers_up=50 --nJammers_dw=0 --JammerType=3 --nDevices=50 --PayloadSize=42 --Specific_SF=1 --ED_SF=7 --simulationTime=3600 --PayloadJamSize_up=42 --JammerTxPower=14 --Random_SF=0 --JammerDutyCycle_up=0.1 --JammerSF=7 --updw=0 --authpre=0 --Exponential=1 --Int_Model=4 --delta=6 --retransmission=1 --maxtx=1 --Conf_UP=1 --Net_Ser=1 --EWMA=true --lambda=0.2"

**Comment by MarinoMtz** [comment]
Hello, EWMA is only for detection on an ongoing attack. It is normal you have the same results. 
  
   
 
  
      Ivan Marino MARTINEZ BOLIVARPost-doctorant- Technopôle Brest-Iroise CS 8381829238 Brest Cedex 3La Chantrerie 4 rue Alfred Kastler BP 2072244307 Nantes Cedex 32, rue de la Châtaigneraie CS 1760835576 Cesson Sévigné CedexUne école de l'IMT       

   

-----Message original-----

De: is-sim ***@***.***>
à: MarinoMtz ***@***.***>
Cc: Subscribed ***@***.***>
Envoyé: lundi 28 mars 2022 12:05 CEST
Sujet : [MarinoMtz/lorawan_jamming] EWMA doesn't work? (Issue #3)

 

  Hi marino, I have run two different simulations: one by activating the EWMA parameter and the other by deactivating this parameter but the result of the two simulations is same. Can you explain me why? Could you give me the right command to correctly activate the EWMA detection algorithm? Thanks
BR 1 simulation) ./waf --run "scratch/lorawan-network-attack-multiple-GW --nGateways=2 --nJammers_up=50 --nJammers_dw=0 --JammerType=3 --nDevices=50 --PayloadSize=42 --Specific_SF=1 --ED_SF=7 --simulationTime=3600 --PayloadJamSize_up=42 --JammerTxPower=14 --Random_SF=0 --JammerDutyCycle_up=0.1 --JammerSF=7 --updw=0 --authpre=0 --Exponential=1 --Int_Model=4 --delta=6 --retransmission=1 --maxtx=1 --Conf_UP=1 --Net_Ser=1" 2 simulation) ./waf --run "scratch/lorawan-network-attack-multiple-GW --nGateways=2 --nJammers_up=50 --nJammers_dw=0 --JammerType=3 --nDevices=50 --PayloadSize=42 --Specific_SF=1 --ED_SF=7 --simulationTime=3600 --PayloadJamSize_up=42 --JammerTxPower=14 --Random_SF=0 --JammerDutyCycle_up=0.1 --JammerSF=7 --updw=0 --authpre=0 --Exponential=1 --Int_Model=4 --delta=6 --retransmission=1 --maxtx=1 --Conf_UP=1 --Net_Ser=1 --EWMA=true --lambda=0.2" —
